# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login_view.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoginView(object):
    def setupUi(self, LoginView):
        LoginView.setObjectName("LoginView")
        LoginView.resize(1600, 775)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginView.sizePolicy().hasHeightForWidth())
        LoginView.setSizePolicy(sizePolicy)
        LoginView.setMinimumSize(QtCore.QSize(1600, 775))
        LoginView.setMaximumSize(QtCore.QSize(1600, 775))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        LoginView.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(LoginView)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1610, 830))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(140, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 6, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 4, 1, 1, 1)
        self.registerLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.registerLabel.setFont(font)
        self.registerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.registerLabel.setObjectName("registerLabel")
        self.gridLayout_2.addWidget(self.registerLabel, 8, 2, 1, 1)
        self.forgotLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.forgotLabel.setFont(font)
        self.forgotLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.forgotLabel.setObjectName("forgotLabel")
        self.gridLayout_2.addWidget(self.forgotLabel, 7, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(500, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 2, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(500, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 3, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 300, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 9, 0, 1, 5)
        spacerItem7 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 8, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 7, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 7, 3, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 4, 3, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 8, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem12, 6, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem13, 4, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem14, 4, 4, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem15, 6, 4, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem16, 3, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem17, 1, 4, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem18, 3, 4, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem19, 3, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem20, 0, 0, 1, 5)
        self.loginPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginPushButton.sizePolicy().hasHeightForWidth())
        self.loginPushButton.setSizePolicy(sizePolicy)
        self.loginPushButton.setMinimumSize(QtCore.QSize(200, 0))
        self.loginPushButton.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loginPushButton.setFont(font)
        self.loginPushButton.setObjectName("loginPushButton")
        self.gridLayout_2.addWidget(self.loginPushButton, 6, 2, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem21 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem21, 7, 4, 1, 1)
        self.logoLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.gridLayout_2.addWidget(self.logoLabel, 1, 1, 1, 3)
        self.passwordLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout_2.addWidget(self.passwordLabel, 2, 1, 1, 3)
        spacerItem22 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem22, 7, 0, 1, 1)
        self.usernameLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.usernameLineEdit.setFont(font)
        self.usernameLineEdit.setText("")
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.gridLayout_2.addWidget(self.usernameLineEdit, 3, 2, 1, 1)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setText("")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout_2.addWidget(self.passwordLineEdit, 4, 2, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem23, 8, 4, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem24, 8, 0, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(140, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem25, 6, 1, 1, 1)
        self.incorrectLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.incorrectLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.incorrectLabel.setFont(font)
        self.incorrectLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.incorrectLabel.setObjectName("incorrectLabel")
        self.gridLayout_2.addWidget(self.incorrectLabel, 5, 2, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(140, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem26, 5, 1, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(140, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem27, 5, 3, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem28, 5, 4, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem29, 5, 0, 1, 1)

        self.retranslateUi(LoginView)
        QtCore.QMetaObject.connectSlotsByName(LoginView)

    def retranslateUi(self, LoginView):
        _translate = QtCore.QCoreApplication.translate
        LoginView.setWindowTitle(_translate("LoginView", "Form"))
        self.registerLabel.setText(_translate("LoginView", "Don\'t have a GAIT Account? Create one now."))
        self.forgotLabel.setText(_translate("LoginView", "Forgotten your username or password?"))
        self.loginPushButton.setText(_translate("LoginView", "Sign In"))
        self.logoLabel.setText(_translate("LoginView", "Logo"))
        self.passwordLabel.setText(_translate("LoginView", "Account Log In"))
        self.usernameLineEdit.setPlaceholderText(_translate("LoginView", "Username"))
        self.passwordLineEdit.setPlaceholderText(_translate("LoginView", "Password"))
        self.incorrectLabel.setText(_translate("LoginView", "Incorrect Username or Password entered!"))

