# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'live_view.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LiveView(object):
    def setupUi(self, LiveView):
        LiveView.setObjectName("LiveView")
        LiveView.resize(1600, 775)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LiveView.sizePolicy().hasHeightForWidth())
        LiveView.setSizePolicy(sizePolicy)
        LiveView.setMinimumSize(QtCore.QSize(1600, 775))
        LiveView.setMaximumSize(QtCore.QSize(1600, 775))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        LiveView.setFont(font)
        LiveView.setStyleSheet("QGroupBox {color: rgb(188, 188, 188); }\n"
"\n"
"QRadioButton {color: rgb(188, 188, 188); margin-top: 11px; margin-bottom: 2px; margin-left: 50px }\n"
"\n"
"QTextEdit {background-color: rgb(39, 39, 52); color: white}\n"
"")
        self.liveStackedWidget = QtWidgets.QStackedWidget(LiveView)
        self.liveStackedWidget.setGeometry(QtCore.QRect(0, 0, 1601, 771))
        self.liveStackedWidget.setObjectName("liveStackedWidget")
        self.defaultView = QtWidgets.QWidget()
        self.defaultView.setObjectName("defaultView")
        self.gridLayoutWidget = QtWidgets.QWidget(self.defaultView)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1601, 771))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.defaultLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.defaultLabel.setFont(font)
        self.defaultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.defaultLabel.setObjectName("defaultLabel")
        self.gridLayout.addWidget(self.defaultLabel, 0, 0, 1, 1)
        self.liveStackedWidget.addWidget(self.defaultView)
        self.connectedView = QtWidgets.QWidget()
        self.connectedView.setObjectName("connectedView")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.connectedView)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 1603, 827))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.viewModeGroupBox = QtWidgets.QGroupBox(self.gridLayoutWidget_2)
        self.viewModeGroupBox.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.viewModeGroupBox.setFont(font)
        self.viewModeGroupBox.setMouseTracking(False)
        self.viewModeGroupBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.viewModeGroupBox.setTitle("")
        self.viewModeGroupBox.setCheckable(False)
        self.viewModeGroupBox.setObjectName("viewModeGroupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.viewModeGroupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1491, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.verticalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.testRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.testRadioButton.setFont(font)
        self.testRadioButton.setChecked(True)
        self.testRadioButton.setObjectName("testRadioButton")
        self.horizontalLayout.addWidget(self.testRadioButton)
        self.dummyMotionRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dummyMotionRadioButton.setFont(font)
        self.dummyMotionRadioButton.setChecked(False)
        self.dummyMotionRadioButton.setObjectName("dummyMotionRadioButton")
        self.horizontalLayout.addWidget(self.dummyMotionRadioButton)
        self.liveMotionRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.liveMotionRadioButton.setFont(font)
        self.liveMotionRadioButton.setObjectName("liveMotionRadioButton")
        self.horizontalLayout.addWidget(self.liveMotionRadioButton)
        self.uvRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.uvRadioButton.setFont(font)
        self.uvRadioButton.setObjectName("uvRadioButton")
        self.horizontalLayout.addWidget(self.uvRadioButton)
        self.gridLayout_2.addWidget(self.viewModeGroupBox, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 3, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 3, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 3, 0, 1, 3)
        self.stackedWidget = QtWidgets.QStackedWidget(self.gridLayoutWidget_2)
        self.stackedWidget.setMinimumSize(QtCore.QSize(1500, 630))
        self.stackedWidget.setObjectName("stackedWidget")
        self.consoleWidget = QtWidgets.QWidget()
        self.consoleWidget.setObjectName("consoleWidget")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.consoleWidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 1502, 632))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.consoleTextEdit = QtWidgets.QTextEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.consoleTextEdit.sizePolicy().hasHeightForWidth())
        self.consoleTextEdit.setSizePolicy(sizePolicy)
        self.consoleTextEdit.setMinimumSize(QtCore.QSize(1500, 630))
        self.consoleTextEdit.setMaximumSize(QtCore.QSize(1500, 630))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.consoleTextEdit.setFont(font)
        self.consoleTextEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.consoleTextEdit.setReadOnly(True)
        self.consoleTextEdit.setObjectName("consoleTextEdit")
        self.gridLayout_3.addWidget(self.consoleTextEdit, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.consoleWidget)
        self.dummyWidget = QtWidgets.QWidget()
        self.dummyWidget.setObjectName("dummyWidget")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.dummyWidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 1502, 632))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.dummyView = PlotWidget(self.gridLayoutWidget_4)
        self.dummyView.setObjectName("dummyView")
        self.gridLayout_5.addWidget(self.dummyView, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.dummyWidget)
        self.liveWidget = QtWidgets.QWidget()
        self.liveWidget.setObjectName("liveWidget")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.liveWidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 1536, 632))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.stepsTitleLabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(15)
        self.stepsTitleLabel.setFont(font)
        self.stepsTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stepsTitleLabel.setObjectName("stepsTitleLabel")
        self.gridLayout_6.addWidget(self.stepsTitleLabel, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem4, 3, 0, 1, 4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem5, 1, 3, 2, 1)
        self.accView = PlotWidget(self.gridLayoutWidget_5)
        self.accView.setMinimumSize(QtCore.QSize(730, 0))
        self.accView.setMaximumSize(QtCore.QSize(730, 16777215))
        self.accView.setObjectName("accView")
        self.gridLayout_6.addWidget(self.accView, 0, 3, 1, 1)
        self.gyroView = PlotWidget(self.gridLayoutWidget_5)
        self.gyroView.setMinimumSize(QtCore.QSize(730, 0))
        self.gyroView.setMaximumSize(QtCore.QSize(730, 16777215))
        self.gyroView.setObjectName("gyroView")
        self.gridLayout_6.addWidget(self.gyroView, 0, 0, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem6, 1, 0, 1, 2)
        self.stepsLabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(15)
        self.stepsLabel.setFont(font)
        self.stepsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.stepsLabel.setObjectName("stepsLabel")
        self.gridLayout_6.addWidget(self.stepsLabel, 2, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem7, 0, 2, 3, 1)
        self.stackedWidget.addWidget(self.liveWidget)
        self.uvWidget = QtWidgets.QWidget()
        self.uvWidget.setObjectName("uvWidget")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.uvWidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 1501, 631))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.uvView = PlotWidget(self.gridLayoutWidget_6)
        self.uvView.setObjectName("uvView")
        self.gridLayout_4.addWidget(self.uvView, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.uvWidget)
        self.gridLayout_2.addWidget(self.stackedWidget, 2, 1, 1, 1)
        self.stackedWidget.raise_()
        self.viewModeGroupBox.raise_()
        self.liveStackedWidget.addWidget(self.connectedView)

        self.retranslateUi(LiveView)
        self.liveStackedWidget.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LiveView)

    def retranslateUi(self, LiveView):
        _translate = QtCore.QCoreApplication.translate
        LiveView.setWindowTitle(_translate("LiveView", "Form"))
        self.defaultLabel.setText(_translate("LiveView", "Please connect to a GAIT device to view live data"))
        self.testRadioButton.setText(_translate("LiveView", "Port Test"))
        self.dummyMotionRadioButton.setText(_translate("LiveView", "Dummy Motion"))
        self.liveMotionRadioButton.setText(_translate("LiveView", "Live Motion"))
        self.uvRadioButton.setText(_translate("LiveView", "UV Exposure"))
        self.stepsTitleLabel.setText(_translate("LiveView", "Steps:"))
        self.stepsLabel.setText(_translate("LiveView", "0"))

from pyqtgraph import PlotWidget
