# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login_view.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoginView(object):
    def setupUi(self, LoginView):
        LoginView.setObjectName("LoginView")
        LoginView.resize(1600, 775)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginView.sizePolicy().hasHeightForWidth())
        LoginView.setSizePolicy(sizePolicy)
        LoginView.setMinimumSize(QtCore.QSize(1600, 775))
        LoginView.setMaximumSize(QtCore.QSize(1600, 775))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        LoginView.setFont(font)
        LoginView.setStyleSheet("QWidget#LoginView {background: qlineargradient(x1: 0, y1: 0, x2: 0.9, y2: 0.8,\n"
"                                stop: 0 rgb(39, 39, 52), stop: 1 rgb(90, 90, 121));\n"
"}\n"
"\n"
"QPushButton { \n"
"    color: white;\n"
"    background-color: rgba(90, 90, 121, 240);\n"
"    border-radius: 2px; \n"
"    border: 1px double rgba(188, 188, 188, 100);\n"
"}\n"
"\n"
"QPushButton::hover{ background-color: rgb(100, 100, 131); }\n"
"\n"
"QLabel { color: rgb(188, 188, 188); }\n"
"\n"
"QLineEdit { \n"
"    border-width: 3px; \n"
"    border-style: solid;\n"
"    border-color: rgb(29, 29, 42);\n"
"    border-radius: 8px;\n"
"    padding: 3px;\n"
"    background-color: rgb(90, 90, 121);\n"
"}\n"
"")
        self.verticalLayoutWidget = QtWidgets.QWidget(LoginView)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1617, 945))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.loginGridLayout = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.loginGridLayout.setContentsMargins(0, 0, 0, 0)
        self.loginGridLayout.setObjectName("loginGridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 180, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.loginGridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.loginGridLayout.addItem(spacerItem1, 3, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.loginGridLayout.addItem(spacerItem2, 4, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.loginGridLayout.addItem(spacerItem3, 7, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(500, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.loginGridLayout.addItem(spacerItem4, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.loginGridLayout.addItem(spacerItem5, 8, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.loginGridLayout.addItem(spacerItem6, 7, 3, 1, 1)
        self.forgotLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setUnderline(True)
        self.forgotLabel.setFont(font)
        self.forgotLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.forgotLabel.setObjectName("forgotLabel")
        self.loginGridLayout.addWidget(self.forgotLabel, 7, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 300, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.loginGridLayout.addItem(spacerItem7, 9, 0, 1, 5)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setStyleSheet("")
        self.passwordLineEdit.setText("")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.loginGridLayout.addWidget(self.passwordLineEdit, 4, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(140, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.loginGridLayout.addItem(spacerItem8, 6, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.loginGridLayout.addItem(spacerItem9, 3, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 180, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.loginGridLayout.addItem(spacerItem10, 1, 4, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.loginGridLayout.addItem(spacerItem11, 4, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.loginGridLayout.addItem(spacerItem12, 4, 3, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.loginGridLayout.addItem(spacerItem13, 6, 4, 1, 1)
        self.usernameLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        self.usernameLineEdit.setFont(font)
        self.usernameLineEdit.setStyleSheet("")
        self.usernameLineEdit.setText("")
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.loginGridLayout.addWidget(self.usernameLineEdit, 3, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.loginGridLayout.addItem(spacerItem14, 7, 0, 1, 1)
        self.registerLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setUnderline(True)
        self.registerLabel.setFont(font)
        self.registerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.registerLabel.setObjectName("registerLabel")
        self.loginGridLayout.addWidget(self.registerLabel, 8, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(500, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.loginGridLayout.addItem(spacerItem15, 2, 4, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(140, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.loginGridLayout.addItem(spacerItem16, 5, 1, 1, 1)
        self.incorrectLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.incorrectLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        self.incorrectLabel.setFont(font)
        self.incorrectLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.incorrectLabel.setObjectName("incorrectLabel")
        self.loginGridLayout.addWidget(self.incorrectLabel, 5, 2, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(140, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.loginGridLayout.addItem(spacerItem17, 5, 3, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(140, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.loginGridLayout.addItem(spacerItem18, 6, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.loginGridLayout.addItem(spacerItem19, 5, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.loginGridLayout.addItem(spacerItem20, 5, 4, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.loginGridLayout.addItem(spacerItem21, 8, 0, 1, 1)
        self.loginLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.loginLabel.setFont(font)
        self.loginLabel.setAutoFillBackground(False)
        self.loginLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loginLabel.setObjectName("loginLabel")
        self.loginGridLayout.addWidget(self.loginLabel, 2, 1, 1, 3)
        spacerItem22 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.loginGridLayout.addItem(spacerItem22, 8, 4, 1, 1)
        self.loginPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginPushButton.sizePolicy().hasHeightForWidth())
        self.loginPushButton.setSizePolicy(sizePolicy)
        self.loginPushButton.setMinimumSize(QtCore.QSize(200, 0))
        self.loginPushButton.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(12)
        self.loginPushButton.setFont(font)
        self.loginPushButton.setObjectName("loginPushButton")
        self.loginGridLayout.addWidget(self.loginPushButton, 6, 2, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem23 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.loginGridLayout.addItem(spacerItem23, 8, 1, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.loginGridLayout.addItem(spacerItem24, 7, 4, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.loginGridLayout.addItem(spacerItem25, 0, 0, 1, 5)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.loginGridLayout.addItem(spacerItem26, 3, 0, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.loginGridLayout.addItem(spacerItem27, 4, 4, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.loginGridLayout.addItem(spacerItem28, 3, 4, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.loginGridLayout.addItem(spacerItem29, 6, 0, 1, 1)
        self.logoLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/icons/logo (with slogan) - big.png"))
        self.logoLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.loginGridLayout.addWidget(self.logoLabel, 1, 1, 1, 3)
        self.incorrectLabel.raise_()
        self.loginLabel.raise_()
        self.loginPushButton.raise_()
        self.usernameLineEdit.raise_()
        self.passwordLineEdit.raise_()
        self.registerLabel.raise_()
        self.forgotLabel.raise_()
        self.logoLabel.raise_()

        self.retranslateUi(LoginView)
        QtCore.QMetaObject.connectSlotsByName(LoginView)
        LoginView.setTabOrder(self.usernameLineEdit, self.passwordLineEdit)
        LoginView.setTabOrder(self.passwordLineEdit, self.loginPushButton)

    def retranslateUi(self, LoginView):
        _translate = QtCore.QCoreApplication.translate
        LoginView.setWindowTitle(_translate("LoginView", "Form"))
        self.forgotLabel.setText(_translate("LoginView", "Forgotten your username or password?"))
        self.passwordLineEdit.setPlaceholderText(_translate("LoginView", "Password"))
        self.usernameLineEdit.setWhatsThis(_translate("LoginView", "<html><head/><body><p>Enter your GAIT Username. If you don\'t have one, create one using the link below</p></body></html>"))
        self.usernameLineEdit.setPlaceholderText(_translate("LoginView", "Username"))
        self.registerLabel.setText(_translate("LoginView", "Don\'t have a GAIT Account? Create one now."))
        self.incorrectLabel.setText(_translate("LoginView", "Incorrect Username or Password entered!"))
        self.loginLabel.setText(_translate("LoginView", "Account Log In"))
        self.loginPushButton.setText(_translate("LoginView", "Sign In"))

import resources_rc
